/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GenerarReportes;


import com.itextpdf.text.BaseColor;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.ColumnText;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfPageEventHelper;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import com.itextpdf.text.Element;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Gael
 */
/**
 * Clase que representa la ventana para mostrar el reporte de clientes frecuentes.
 * Esta clase extiende `JFrame` y permite realizar búsquedas de clientes frecuentes 
 * mediante filtros de nombre y visitas. Además, permite generar un reporte en formato PDF.
 */
public class ReporteReservaciones extends javax.swing.JFrame {
   
    /**
     * Creates new form ReporteClientesFrecuentes
     */
        /**
     * Constructor que inicializa la ventana y configura los componentes de la interfaz.
     * Inicializa los objetos de coordinación y los listeners para los campos de búsqueda.
     */
    public ReporteReservaciones() {
        initComponents();
       
    }
        /**
     * Método que agrega listeners a los campos de texto para realizar la búsqueda en tiempo real.
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        visitasLabel = new javax.swing.JLabel();
        visitasTextField = new javax.swing.JTextField();
        tabla = new javax.swing.JScrollPane();
        tablaMostrarClientesFrecuentes = new javax.swing.JTable();
        botonRegresar = new javax.swing.JButton();
        botonGenerarPDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setText("Reporte de clientes frecuentes");

        nombreLabel.setText("Nombre:");

        visitasLabel.setText("Visitas:");

        tablaMostrarClientesFrecuentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Visitas", "Total gastado", "Puntos", "Ultima comanda"
            }
        ));
        tabla.setViewportView(tablaMostrarClientesFrecuentes);

        botonRegresar.setBackground(new java.awt.Color(27, 61, 174));
        botonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        botonGenerarPDF.setBackground(new java.awt.Color(27, 61, 174));
        botonGenerarPDF.setForeground(new java.awt.Color(255, 255, 255));
        botonGenerarPDF.setText("Generar PDF");
        botonGenerarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addGap(162, 162, 162))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreLabel)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visitasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visitasLabel))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabla)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonGenerarPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreLabel)
                            .addComponent(visitasLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(visitasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonGenerarPDF, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      /**
     * Método que maneja el evento del botón "Regresar" para cerrar la ventana y mostrar el menú de reportes.
     * @param evt Evento del botón "Regresar".
     */
    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed
  
        /**
     * Clase interna que define el numerador de páginas para el reporte en PDF.
     * Extiende `PdfPageEventHelper` para insertar el número de página en el pie de página de cada página del PDF.
     */
    public class NumeradorPaginas extends PdfPageEventHelper {
    private Font fuente = FontFactory.getFont(FontFactory.HELVETICA, 9, Font.NORMAL, BaseColor.GRAY);

    @Override
    public void onEndPage(PdfWriter writer, Document document) {
        PdfContentByte cb = writer.getDirectContent();
        Phrase pie = new Phrase("Página " + writer.getPageNumber(), fuente);
        ColumnText.showTextAligned(cb, Element.ALIGN_CENTER,
                pie,
                (document.right() - document.left()) / 2 + document.leftMargin(),
                document.bottom() - 10, 0);
    }
}

       /**
     * Método que maneja el evento del botón "Generar PDF" para generar un reporte en formato PDF con los clientes frecuentes.
     * @param evt Evento del botón "Generar PDF".
     */
    private void botonGenerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarPDFActionPerformed
        // TODO add your handling code here:
        Document documento = new Document();
        
        try {
            //sino les genera el pdf seguramente puede variar por la ruta, asi que cuidado con eso.
            ///////////////////////////////////////////////////////////////////////////////////////
            String ruta = System.getProperty("user.home");
            PdfWriter writer = PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/ReporteClientesFrecuentes.pdf"));
            writer.setPageEvent(new NumeradorPaginas());
            documento.open();
            //titulo
            Paragraph titulo = new Paragraph("REPORTE DE CLIENTES FRECUENTES\n\n");
            titulo.setAlignment(Element.ALIGN_CENTER);
            documento.add(titulo);
            //fecha
            String fechaActual = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(new Date());
            Paragraph fecha = new Paragraph("Fecha de generación: " + fechaActual);
            fecha.setAlignment(Element.ALIGN_RIGHT);
            documento.add(fecha);
            documento.add(new Paragraph("\n"));
            
            PdfPTable tabla = new PdfPTable(5);
            tabla.setWidthPercentage(100);
            tabla.addCell("Nombre");
            tabla.addCell("Cantidad de Visitas");
            tabla.addCell("Total gastado");
            tabla.addCell("Puntos");
            tabla.addCell("Ultima comanda");
            for (int i = 0; i< tablaMostrarClientesFrecuentes.getRowCount(); i++) {
                String nombre = tablaMostrarClientesFrecuentes.getValueAt(i,0).toString();
                String visitas = tablaMostrarClientesFrecuentes.getValueAt(i, 1).toString();
                String total = tablaMostrarClientesFrecuentes.getValueAt(i, 2).toString();
                String puntos = tablaMostrarClientesFrecuentes.getValueAt(i, 3).toString();
                String ultimaComanda = tablaMostrarClientesFrecuentes.getValueAt(i, 4).toString();
                tabla.addCell(nombre);
                tabla.addCell(visitas);
                tabla.addCell(total);
                tabla.addCell(puntos);
                tabla.addCell(ultimaComanda);
            }
            documento.add(tabla);
            documento.close();
            JOptionPane.showMessageDialog(this, "PDF generado con éxito en el escritorio.");
           
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al generar el PDF" + e.getMessage());
        }
    }//GEN-LAST:event_botonGenerarPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteReservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteReservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteReservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteReservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteReservaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGenerarPDF;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JScrollPane tabla;
    private javax.swing.JTable tablaMostrarClientesFrecuentes;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel visitasLabel;
    private javax.swing.JTextField visitasTextField;
    // End of variables declaration//GEN-END:variables
}
