/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import controlReservacion.GestorReservacion;
import dtos.MesaDTO;
import java.awt.Color;
import java.util.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import objetosnegocio.MesaON;

/**
 *
 * @author Gael
 */
public class MapadeMesas extends javax.swing.JFrame {
    private static MapadeMesas instancia;
   private GestorReservacion negocioReservacion;
   
   private MesaDTO mesaSeleccionada;
   
   public MesaDTO getMesaSeleccionada() {
    return mesaSeleccionada;
}
    public static MapadeMesas getInstance() {
        if (instancia == null) {
            instancia = new MapadeMesas();
        }
        return instancia;
    }
   
    
    /**
     * Creates new form MapadeMesas
     */
    public MapadeMesas() {
        initComponents();
        negocioReservacion = new GestorReservacion();
        cargarMesasDisponibles();
        
    }
    public void actualizarEstadoMesas() {
    List<MesaDTO> mesas = new ArrayList<>(MesaON.getInstance().cargarMesas());
    if (mesas != null && mesas.size() >= 7) {
        configurarMesa(mesa1, MesaON.getInstance().obtenerMesa(1));
        configurarMesa(mesa2, MesaON.getInstance().obtenerMesa(2));
        configurarMesa(mesa3, MesaON.getInstance().obtenerMesa(3));
        configurarMesa(mesa4, MesaON.getInstance().obtenerMesa(4));
        configurarMesa(mesa5, MesaON.getInstance().obtenerMesa(5));
        configurarMesa(mesa6, MesaON.getInstance().obtenerMesa(6));
        configurarMesa(mesa7, MesaON.getInstance().obtenerMesa(7));
    }
}

    private void cargarMesasDisponibles() {
    List<MesaDTO> mesas = new ArrayList<>(MesaON.getInstance().cargarMesas());
    if (mesas != null && mesas.size() >= 7) {
        configurarMesa(mesa1, MesaON.getInstance().obtenerMesa(1));
        configurarMesa(mesa2, MesaON.getInstance().obtenerMesa(2));
        configurarMesa(mesa3, MesaON.getInstance().obtenerMesa(3));
        configurarMesa(mesa4, MesaON.getInstance().obtenerMesa(4));
        configurarMesa(mesa5, MesaON.getInstance().obtenerMesa(5));
        configurarMesa(mesa6, MesaON.getInstance().obtenerMesa(6));
        configurarMesa(mesa7, MesaON.getInstance().obtenerMesa(7));
    }

        
        
}
    private void abrirRegistrarReservacion(MesaDTO mesa) {
    RegistrarReservacion registrarReservacion = new RegistrarReservacion();
    registrarReservacion.setMesaSeleccionada(mesa);
    registrarReservacion.setLocationRelativeTo(null);
    registrarReservacion.setVisible(true); 
    this.dispose();
}
        
    private void configurarMesa(JButton mesaBtn, MesaDTO mesa) {
    mesaBtn.setText("Mesa " + mesa.getNumeroMesa());
    if (mesa.isDisponible()) {
        mesaBtn.setBackground(Color.GREEN);  
        mesaBtn.setEnabled(true);
    } else {
        mesaBtn.setBackground(Color.RED);  
        mesaBtn.setEnabled(false);
    }

    mesaBtn.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            MesaDTO mesaActualizada = MesaON.getInstance().obtenerMesa(mesa.getNumeroMesa()); // Obtener la referencia actualizada
            if (mesaActualizada.isDisponible()) {
                mesaSeleccionada = mesaActualizada;
                JOptionPane.showMessageDialog(MapadeMesas.this, "Mesa " + mesaActualizada.getNumeroMesa() + " seleccionada.");
                RegistrarReservacion registrarReservacion = new RegistrarReservacion();
                registrarReservacion.setMesaSeleccionada(mesaActualizada);
                registrarReservacion.setLocationRelativeTo(null); 
                registrarReservacion.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(MapadeMesas.this, "La mesa " + mesaActualizada.getNumeroMesa() + " está ocupada.");
            }
        }
    });
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        mesa1 = new javax.swing.JButton();
        mesa2 = new javax.swing.JButton();
        mesa3 = new javax.swing.JButton();
        mesa4 = new javax.swing.JButton();
        mesa5 = new javax.swing.JButton();
        mesa6 = new javax.swing.JButton();
        mesa7 = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        mesa1.setText("Mesa 1");
        mesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesa1ActionPerformed(evt);
            }
        });

        mesa2.setText("Mesa 2");

        mesa3.setText("Mesa 3");

        mesa4.setText("Mesa 4");

        mesa5.setText("Mesa 5");

        mesa6.setText("Mesa 6");

        mesa7.setText("Mesa 7");

        btnRegresar.setBackground(new java.awt.Color(204, 255, 204));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(mesa2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(mesa4)
                        .addGap(107, 107, 107)
                        .addComponent(mesa5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mesa1)
                            .addComponent(btnRegresar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(126, Short.MAX_VALUE)
                        .addComponent(mesa7)
                        .addGap(121, 121, 121)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mesa6)
                            .addComponent(mesa3))))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mesa1)
                    .addComponent(mesa3))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mesa2)
                                .addGap(68, 68, 68)
                                .addComponent(mesa4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(mesa5)))
                        .addGap(9, 9, 9)
                        .addComponent(mesa6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(btnRegresar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mesa7)
                        .addGap(93, 93, 93))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Coordinador.CoordinadorPantallas.getInstance().mostrarPantallaInicio();
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void mesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesa1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapadeMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapadeMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapadeMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapadeMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapadeMesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mesa1;
    private javax.swing.JButton mesa2;
    private javax.swing.JButton mesa3;
    private javax.swing.JButton mesa4;
    private javax.swing.JButton mesa5;
    private javax.swing.JButton mesa6;
    private javax.swing.JButton mesa7;
    // End of variables declaration//GEN-END:variables
}
