/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author Gael
 */
public class PantallaMenu extends javax.swing.JFrame {

    /**
     * Creates new form PantallaInicio
     */
    public PantallaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BotonReservar = new javax.swing.JButton();
        BotonMapaMesas = new javax.swing.JButton();
        btnRegistrarCliente = new javax.swing.JButton();
        btnMeseros = new javax.swing.JButton();
        btnCancelarReservacion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bienvenido");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));

        BotonReservar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        BotonReservar.setText("Reservar");
        BotonReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReservarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonReservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 160, 60));

        BotonMapaMesas.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        BotonMapaMesas.setText("Mapa Mesas");
        BotonMapaMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMapaMesasActionPerformed(evt);
            }
        });
        getContentPane().add(BotonMapaMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 180, 70));

        btnRegistrarCliente.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnRegistrarCliente.setText("Registrar Cliente");
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 180, 60));

        btnMeseros.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnMeseros.setText("Meseros");
        btnMeseros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeserosActionPerformed(evt);
            }
        });
        getContentPane().add(btnMeseros, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 140, 60));

        btnCancelarReservacion.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnCancelarReservacion.setText("Cancelar Reservacion");
        btnCancelarReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarReservacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 220, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondoResta.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReservarActionPerformed
        // TODO add your handling code here:
        Coordinador.CoordinadorPantallas.getInstance().mostrarMapaMesas();
        dispose();
    }//GEN-LAST:event_BotonReservarActionPerformed

    private void BotonMapaMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMapaMesasActionPerformed
        // TODO add your handling code here:
        Coordinador.CoordinadorPantallas.getInstance().mostrarMapaMesas();
        dispose();
    }//GEN-LAST:event_BotonMapaMesasActionPerformed

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void btnMeserosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeserosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMeserosActionPerformed

    private void btnCancelarReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarReservacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarReservacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaMenu().setVisible(true);
                new PantallaMenu().setLocationRelativeTo(null);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonMapaMesas;
    private javax.swing.JButton BotonReservar;
    private javax.swing.JButton btnCancelarReservacion;
    private javax.swing.JButton btnMeseros;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
