/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import controlReservacion.GestorReservacion;
import dtos.MesaDTO;
import dtos.MeseroDTO;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.mail.PasswordAuthentication;
import javax.mail.Transport;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import objetosnegocio.MeseroON;

/**
 *
 * @author Gael
 */
public class RegistrarReservacion extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarReservacion
     */
    private MesaDTO mesa;
    private List<MeseroDTO> listaMeseros;
    public static MapadeMesas mapaDeMesas;
    private LocalDate fechaSeleccionada;
    private LocalTime horaSeleccionada;
    private String emailFrom = "restaurantedisoftware@gmail.com";
    private String password = "bjxk3801";
    private String mailTo;
    private String subject;
    private String conent;
    private Authenticator auth;
    private Properties propierties;
    //private File[] adjuntos;
    
    
        public void setMesaSeleccionada(MesaDTO mesa) {
        this.mesa = mesa;
        mostrarDetallesMesa();
    }
        public void setFechaHoraSeleccionada (LocalDate fecha, LocalTime hora){
        this.fechaSeleccionada = fecha;
        this.horaSeleccionada = hora;
        labelFechaSeleccionada.setText("Fecha seleccionada: " +  fecha.toString());
        labelHoraSeleccionada.setText("Hora seleccionada: " + hora.toString());
        
        
        }
        private void mostrarDetallesMesa() {
            if (mesa != null) {
                jLabelNumeroMesa.setText("Mesa " + mesa.getNumeroMesa());
            }else{
            JOptionPane.showMessageDialog(this, "Error al mostrar mesa." + JOptionPane.ERROR_MESSAGE);
            }
    }
    public RegistrarReservacion() {
        initComponents();
        cargarMeseros();
        mapaDeMesas = Coordinador.CoordinadorPantallas.getInstance().getMapaDeMesas();
          
    }

    private void cargarMeseros() {
        listaMeseros = MeseroON.getInstance().obtenerMeseros();
  
    for (MeseroDTO mesero : listaMeseros) {
        comboMesero.addItem(mesero.getNombre()); 
    }
}
 public void enviarCorreoConfirmacion(String nombre, String correo, String telefono, int mesa, String fecha, String mesero) {
    String host = "smtp.gmail.com"; 
    final String usuario = "restaurantedisoftware@gmail.com"; 
    final String contrasena = "sotg wpan zyhs bvpj"; 

    // Configuración del servidor SMTP
    Properties propiedades = new Properties();
    propiedades.put("mail.smtp.host", host);
    propiedades.put("mail.smtp.port", "587");
    propiedades.put("mail.smtp.auth", "true");
    propiedades.put("mail.smtp.starttls.enable", "true"); 

    
    Session session = Session.getInstance(propiedades, new Authenticator() {
        protected PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication(usuario, contrasena);
        }
    });

    try {
        
        MimeMessage mensaje = new MimeMessage(session);
        mensaje.setFrom(new InternetAddress(usuario));
        mensaje.addRecipient(Message.RecipientType.TO, new InternetAddress(correo)); 
        mensaje.setSubject("Confirmación de Reservación");
        
        // Cuerpo del correo (Ticket de confirmación)
        String cuerpo = "-------- TICKET DE RESERVACIÓN --------\n"
                        + "Nombre del cliente: " + nombre + "\n"
                        + "Teléfono: " + telefono + "\n"
                        + "Correo: " + correo + "\n"
                        + "Mesa: " + mesa + "\n"
                        + "Fecha de la reservación: " + fecha + "\n"
                        + "Mesero asignado: " + mesero + "\n"
                        + "-------------------------------------\n"
                        + "¡Gracias por tu reservación!";
        
        mensaje.setText(cuerpo);

       
        Transport.send(mensaje);

        System.out.println("Correo enviado correctamente.");

    } catch (MessagingException e) {
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelNumeroMesa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textoNombreCliente = new javax.swing.JTextField();
        textCorreo = new javax.swing.JTextField();
        textoTelefono = new javax.swing.JTextField();
        btnReservar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        comboMesero = new javax.swing.JComboBox<>();
        labelMesero = new javax.swing.JLabel();
        labelFechaSeleccionada = new javax.swing.JLabel();
        labelHoraSeleccionada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Reservacion de Mesa");

        jLabelNumeroMesa.setText("Número de mesa:");

        jLabel3.setText("Nombre cliente:");

        jLabel5.setText("Correo:");

        jLabel6.setText("Telefono:");

        textoTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTelefonoActionPerformed(evt);
            }
        });

        btnReservar.setText("Reservar");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        comboMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMeseroActionPerformed(evt);
            }
        });

        labelMesero.setText("Mesero:");

        labelFechaSeleccionada.setText("jLabel2");

        labelHoraSeleccionada.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelNumeroMesa)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(btnRegresar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReservar)
                                .addGap(54, 54, 54))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelMesero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(comboMesero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textoNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)))
                                .addGap(130, 130, 130)
                                .addComponent(labelFechaSeleccionada))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelHoraSeleccionada)))
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(jLabelNumeroMesa)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboMesero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(labelHoraSeleccionada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelFechaSeleccionada)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservar)
                    .addComponent(btnRegresar))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTelefonoActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        // TODO add your handling code here
        if (mesa == null) {
        JOptionPane.showMessageDialog(this, "No hay una mesa seleccionada.");
        return;
    }
    
    String nombre = textoNombreCliente.getText().trim();
    String telefono = textoTelefono.getText().trim();
    String correo = textCorreo.getText().trim();
    int indice = comboMesero.getSelectedIndex();
    if (indice < 0) {
        JOptionPane.showMessageDialog(this, "Selecciona un mesero.");
        return;
    }
    MeseroDTO meseroSeleccionado = listaMeseros.get(indice);
    
    mesa.setDisponible(false);
    mapaDeMesas.actualizarEstadoMesas();
    mapaDeMesas.repaint();
    
    StringBuilder ticket = new StringBuilder();
    ticket.append("-------- TICKET DE RESERVACIÓN --------\n")
          .append("Nombre del cliente: ").append(nombre).append("\n")
          .append("Teléfono: ").append(telefono).append("\n")
          .append("Correo: ").append(correo).append("\n")
          .append("Mesa: ").append(mesa.getNumeroMesa()).append("\n")
          .append("Mesero asignado: ").append(meseroSeleccionado.getNombre()).append("\n")
          .append("-------------------------------------\n")
          .append("¡Gracias por tu reservación!");
    JOptionPane.showMessageDialog(this, ticket.toString(), "Se envío el ticket de confirmación a su correo.", JOptionPane.INFORMATION_MESSAGE);
       
        enviarCorreoConfirmacion(nombre, correo, telefono, mesa.getNumeroMesa(), fechaSeleccionada.toString(), meseroSeleccionado.getNombre());
    this.dispose();
    mapaDeMesas.setVisible(true);
    mapaDeMesas.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
       Coordinador.CoordinadorPantallas.getInstance().mostrarMapaMesas();
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void comboMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMeseroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMeseroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarReservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarReservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarReservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarReservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                RegistrarReservacion r = new RegistrarReservacion();
                r.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnReservar;
    private javax.swing.JComboBox<String> comboMesero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelNumeroMesa;
    private javax.swing.JLabel labelFechaSeleccionada;
    private javax.swing.JLabel labelHoraSeleccionada;
    private javax.swing.JLabel labelMesero;
    private javax.swing.JTextField textCorreo;
    private javax.swing.JTextField textoNombreCliente;
    private javax.swing.JTextField textoTelefono;
    // End of variables declaration//GEN-END:variables
}
